### ISSUE TITLE
async from kotlinx.coroutines.experimental.asyn OBSOLETE

### ISSUE THREAD

**Issue by lauramsolana93** [deva666/NewsReader#2]
Hi `@deva666,` 

we are doing Kotlin in Practice course from Safari Books, we have notate that async used in file RetrofitExtensions it's obsolete.

Could you bring a solution? we have seen that you might have to do a migration to 1.3 versions of this implementations -> 
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-core:0.19'
implementation 'org.jetbrains.kotlinx:kotlinx-coroutines-android:0.19'

You will find the problem in this line ->
fun <T<T>>  Call<T<T>>.launchAsync(): Deferred<T<T>> = async{this@launchAsync.execute().body()!!}

**Comment by deva666** [comment]
Yes, this is because some Coroutine api has changed in the latest (stable) release.
I didn't want to update it because it will differ then from the code in the course.
I can update it in a different branch.

**Comment by lauramsolana93** [comment]
So, you can do that? it will be very useful for us 

Thanks

**Comment by deva666** [comment]
here is the branch with Kotlin 1.3 and Coroutines 1.0 https://github.com/deva666/NewsReader/tree/kotlin_1.3

**Comment by lauramsolana93** [comment]
Thanks for updating the project :)
